### ISSUE TITLE
stop auto-loading of drafts?

### ISSUE THREAD

**Issue by Dizchord** [MarkusWME/phpBB---Auto-Drafts#1]
Is there a way to disable the automatic loading of the last auto-draft saved? It seems like every time I start a new message on my board it brings up the last message I wrote.

**Comment by MarkusWME** [comment]
A new version is now available which includes some cool new features. Now it is possible to stop the automatic loading of auto drafts.
The new version is available [here](https://github.com/MarkusWME/phpBB---Auto-Drafts/releases/download/v1.1.0/autodrafts-1.1.0.zip "Download Auto Drafts 1.1.0").
